export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USERS_LOGOUT = "USERS_LOGOUT";
export const CLEAR_ALL_USER_MSGS = "CLEAR_ALL_USER_MSGS";
